[package]
name = "intel-spi"
version = "0.1.5"
authors = ["Jeremy Soller <jeremy@system76.com>"]
edition = "2021"
description = "Library for accessing Intel PCH SPI"
license = "MIT"

[dependencies]
bitflags = "1.0.4"
coreboot-fs = "0.1.0"
libc = "0.2"
redox_intelflash = "0.1.2"
